/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as ArenasRouteImport } from './routes/arenas'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DenunciarRouteImport } from './routes/denunciar'
import { Route as EscolherPerfilRouteImport } from './routes/escolher-perfil'
import { Route as JuizRouteImport } from './routes/juiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeusFeedbacksRouteImport } from './routes/meus-feedbacks'
import { Route as MeusJogosRouteImport } from './routes/meus-jogos'
import { Route as MinhasInscricoesRouteImport } from './routes/minhas-inscricoes'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PlacarRouteImport } from './routes/placar'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as TrocarDuplaRouteImport } from './routes/trocar-dupla'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArenasRouteImport } from './routes/admin.arenas'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminFeedbacksRouteImport } from './routes/admin.feedbacks'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminPublicidadeRouteImport } from './routes/admin.publicidade'
import { Route as AdminReembolsosRouteImport } from './routes/admin.reembolsos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as FeedbackSlugRouteImport } from './routes/feedback.$slug'
import { Route as InscricaoSlugRouteImport } from './routes/inscricao.$slug'
import { Route as JogadoresPlayerIdRouteImport } from './routes/jogadores.$playerId'
import { Route as OrganizadorIndexRouteImport } from './routes/organizador.index'
import { Route as OrganizadorControleRouteImport } from './routes/organizador.controle'
import { Route as OrganizadorEventosRouteImport } from './routes/organizador.eventos'
import { Route as OrganizadorFinanceiroRouteImport } from './routes/organizador.financeiro'
import { Route as OrganizadorInscricoesRouteImport } from './routes/organizador.inscricoes'
import { Route as OrganizadorNovoEventoRouteImport } from './routes/organizador.novo-evento'
import { Route as OrganizadorPlanoRouteImport } from './routes/organizador.plano'
import { Route as ReembolsoPaymentIdRouteImport } from './routes/reembolso.$paymentId'
import { Route as AdminDenunciasIndexRouteImport } from './routes/admin.denuncias.index'
import { Route as AdminDenunciasIdRouteImport } from './routes/admin.denuncias.$id'
import { Route as AdminOrganizadoresIndexRouteImport } from './routes/admin.organizadores.index'
import { Route as AdminOrganizadoresIdRouteImport } from './routes/admin.organizadores.$id'
import { Route as AdminPagamentosIndexRouteImport } from './routes/admin.pagamentos.index'
import { Route as AdminPagamentosIdRouteImport } from './routes/admin.pagamentos.$id'
import { Route as OrganizadorAlterarEventoSlugRouteImport } from './routes/organizador.alterar-evento.$slug'
import { Route as OrganizadorSorteioSlugRouteImport } from './routes/organizador.sorteio.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenasRoute = ArenasRouteImport.update({
  id: '/arenas',
  path: '/arenas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciarRoute = DenunciarRouteImport.update({
  id: '/denunciar',
  path: '/denunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherPerfilRoute = EscolherPerfilRouteImport.update({
  id: '/escolher-perfil',
  path: '/escolher-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const JuizRoute = JuizRouteImport.update({
  id: '/juiz',
  path: '/juiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusFeedbacksRoute = MeusFeedbacksRouteImport.update({
  id: '/meus-feedbacks',
  path: '/meus-feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusJogosRoute = MeusJogosRouteImport.update({
  id: '/meus-jogos',
  path: '/meus-jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasInscricoesRoute = MinhasInscricoesRouteImport.update({
  id: '/minhas-inscricoes',
  path: '/minhas-inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacarRoute = PlacarRouteImport.update({
  id: '/placar',
  path: '/placar',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarDuplaRoute = TrocarDuplaRouteImport.update({
  id: '/trocar-dupla',
  path: '/trocar-dupla',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArenasRoute = AdminArenasRouteImport.update({
  id: '/admin/arenas',
  path: '/admin/arenas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/admin/eventos',
  path: '/admin/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbacksRoute = AdminFeedbacksRouteImport.update({
  id: '/admin/feedbacks',
  path: '/admin/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/admin/planos',
  path: '/admin/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPublicidadeRoute = AdminPublicidadeRouteImport.update({
  id: '/admin/publicidade',
  path: '/admin/publicidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReembolsosRoute = AdminReembolsosRouteImport.update({
  id: '/admin/reembolsos',
  path: '/admin/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackSlugRoute = FeedbackSlugRouteImport.update({
  id: '/feedback/$slug',
  path: '/feedback/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoSlugRoute = InscricaoSlugRouteImport.update({
  id: '/inscricao/$slug',
  path: '/inscricao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresPlayerIdRoute = JogadoresPlayerIdRouteImport.update({
  id: '/jogadores/$playerId',
  path: '/jogadores/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorIndexRoute = OrganizadorIndexRouteImport.update({
  id: '/organizador/',
  path: '/organizador/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorControleRoute = OrganizadorControleRouteImport.update({
  id: '/organizador/controle',
  path: '/organizador/controle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorEventosRoute = OrganizadorEventosRouteImport.update({
  id: '/organizador/eventos',
  path: '/organizador/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorFinanceiroRoute = OrganizadorFinanceiroRouteImport.update({
  id: '/organizador/financeiro',
  path: '/organizador/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorInscricoesRoute = OrganizadorInscricoesRouteImport.update({
  id: '/organizador/inscricoes',
  path: '/organizador/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorNovoEventoRoute = OrganizadorNovoEventoRouteImport.update({
  id: '/organizador/novo-evento',
  path: '/organizador/novo-evento',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorPlanoRoute = OrganizadorPlanoRouteImport.update({
  id: '/organizador/plano',
  path: '/organizador/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoPaymentIdRoute = ReembolsoPaymentIdRouteImport.update({
  id: '/reembolso/$paymentId',
  path: '/reembolso/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDenunciasIndexRoute = AdminDenunciasIndexRouteImport.update({
  id: '/admin/denuncias/',
  path: '/admin/denuncias/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDenunciasIdRoute = AdminDenunciasIdRouteImport.update({
  id: '/admin/denuncias/$id',
  path: '/admin/denuncias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizadoresIndexRoute = AdminOrganizadoresIndexRouteImport.update({
  id: '/admin/organizadores/',
  path: '/admin/organizadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizadoresIdRoute = AdminOrganizadoresIdRouteImport.update({
  id: '/admin/organizadores/$id',
  path: '/admin/organizadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagamentosIndexRoute = AdminPagamentosIndexRouteImport.update({
  id: '/admin/pagamentos/',
  path: '/admin/pagamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagamentosIdRoute = AdminPagamentosIdRouteImport.update({
  id: '/admin/pagamentos/$id',
  path: '/admin/pagamentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadorAlterarEventoSlugRoute =
  OrganizadorAlterarEventoSlugRouteImport.update({
    id: '/organizador/alterar-evento/$slug',
    path: '/organizador/alterar-evento/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizadorSorteioSlugRoute = OrganizadorSorteioSlugRouteImport.update({
  id: '/organizador/sorteio/$slug',
  path: '/organizador/sorteio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/arenas': typeof ArenasRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/denunciar': typeof DenunciarRoute
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/juiz': typeof JuizRoute
  '/login': typeof LoginRoute
  '/meus-feedbacks': typeof MeusFeedbacksRoute
  '/meus-jogos': typeof MeusJogosRoute
  '/minhas-inscricoes': typeof MinhasInscricoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiros': typeof ParceirosRoute
  '/placar': typeof PlacarRoute
  '/ranking': typeof RankingRoute
  '/trocar-dupla': typeof TrocarDuplaRoute
  '/admin/arenas': typeof AdminArenasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/publicidade': typeof AdminPublicidadeRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/feedback/$slug': typeof FeedbackSlugRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/jogadores/$playerId': typeof JogadoresPlayerIdRoute
  '/organizador/controle': typeof OrganizadorControleRoute
  '/organizador/eventos': typeof OrganizadorEventosRoute
  '/organizador/financeiro': typeof OrganizadorFinanceiroRoute
  '/organizador/inscricoes': typeof OrganizadorInscricoesRoute
  '/organizador/novo-evento': typeof OrganizadorNovoEventoRoute
  '/organizador/plano': typeof OrganizadorPlanoRoute
  '/reembolso/$paymentId': typeof ReembolsoPaymentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/organizador/': typeof OrganizadorIndexRoute
  '/admin/denuncias/$id': typeof AdminDenunciasIdRoute
  '/admin/organizadores/$id': typeof AdminOrganizadoresIdRoute
  '/admin/pagamentos/$id': typeof AdminPagamentosIdRoute
  '/organizador/alterar-evento/$slug': typeof OrganizadorAlterarEventoSlugRoute
  '/organizador/sorteio/$slug': typeof OrganizadorSorteioSlugRoute
  '/admin/denuncias/': typeof AdminDenunciasIndexRoute
  '/admin/organizadores/': typeof AdminOrganizadoresIndexRoute
  '/admin/pagamentos/': typeof AdminPagamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/arenas': typeof ArenasRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/denunciar': typeof DenunciarRoute
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/juiz': typeof JuizRoute
  '/login': typeof LoginRoute
  '/meus-feedbacks': typeof MeusFeedbacksRoute
  '/meus-jogos': typeof MeusJogosRoute
  '/minhas-inscricoes': typeof MinhasInscricoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiros': typeof ParceirosRoute
  '/placar': typeof PlacarRoute
  '/ranking': typeof RankingRoute
  '/trocar-dupla': typeof TrocarDuplaRoute
  '/admin/arenas': typeof AdminArenasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/publicidade': typeof AdminPublicidadeRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/feedback/$slug': typeof FeedbackSlugRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/jogadores/$playerId': typeof JogadoresPlayerIdRoute
  '/organizador/controle': typeof OrganizadorControleRoute
  '/organizador/eventos': typeof OrganizadorEventosRoute
  '/organizador/financeiro': typeof OrganizadorFinanceiroRoute
  '/organizador/inscricoes': typeof OrganizadorInscricoesRoute
  '/organizador/novo-evento': typeof OrganizadorNovoEventoRoute
  '/organizador/plano': typeof OrganizadorPlanoRoute
  '/reembolso/$paymentId': typeof ReembolsoPaymentIdRoute
  '/admin': typeof AdminIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/organizador': typeof OrganizadorIndexRoute
  '/admin/denuncias/$id': typeof AdminDenunciasIdRoute
  '/admin/organizadores/$id': typeof AdminOrganizadoresIdRoute
  '/admin/pagamentos/$id': typeof AdminPagamentosIdRoute
  '/organizador/alterar-evento/$slug': typeof OrganizadorAlterarEventoSlugRoute
  '/organizador/sorteio/$slug': typeof OrganizadorSorteioSlugRoute
  '/admin/denuncias': typeof AdminDenunciasIndexRoute
  '/admin/organizadores': typeof AdminOrganizadoresIndexRoute
  '/admin/pagamentos': typeof AdminPagamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/arenas': typeof ArenasRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/denunciar': typeof DenunciarRoute
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/juiz': typeof JuizRoute
  '/login': typeof LoginRoute
  '/meus-feedbacks': typeof MeusFeedbacksRoute
  '/meus-jogos': typeof MeusJogosRoute
  '/minhas-inscricoes': typeof MinhasInscricoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/parceiros': typeof ParceirosRoute
  '/placar': typeof PlacarRoute
  '/ranking': typeof RankingRoute
  '/trocar-dupla': typeof TrocarDuplaRoute
  '/admin/arenas': typeof AdminArenasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/publicidade': typeof AdminPublicidadeRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/feedback/$slug': typeof FeedbackSlugRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/jogadores/$playerId': typeof JogadoresPlayerIdRoute
  '/organizador/controle': typeof OrganizadorControleRoute
  '/organizador/eventos': typeof OrganizadorEventosRoute
  '/organizador/financeiro': typeof OrganizadorFinanceiroRoute
  '/organizador/inscricoes': typeof OrganizadorInscricoesRoute
  '/organizador/novo-evento': typeof OrganizadorNovoEventoRoute
  '/organizador/plano': typeof OrganizadorPlanoRoute
  '/reembolso/$paymentId': typeof ReembolsoPaymentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/organizador/': typeof OrganizadorIndexRoute
  '/admin/denuncias/$id': typeof AdminDenunciasIdRoute
  '/admin/organizadores/$id': typeof AdminOrganizadoresIdRoute
  '/admin/pagamentos/$id': typeof AdminPagamentosIdRoute
  '/organizador/alterar-evento/$slug': typeof OrganizadorAlterarEventoSlugRoute
  '/organizador/sorteio/$slug': typeof OrganizadorSorteioSlugRoute
  '/admin/denuncias/': typeof AdminDenunciasIndexRoute
  '/admin/organizadores/': typeof AdminOrganizadoresIndexRoute
  '/admin/pagamentos/': typeof AdminPagamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ao-vivo'
    | '/arenas'
    | '/cadastro'
    | '/configuracoes'
    | '/denunciar'
    | '/escolher-perfil'
    | '/juiz'
    | '/login'
    | '/meus-feedbacks'
    | '/meus-jogos'
    | '/minhas-inscricoes'
    | '/notificacoes'
    | '/onboarding'
    | '/parceiros'
    | '/placar'
    | '/ranking'
    | '/trocar-dupla'
    | '/admin/arenas'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/feedbacks'
    | '/admin/financeiro'
    | '/admin/planos'
    | '/admin/publicidade'
    | '/admin/reembolsos'
    | '/admin/usuarios'
    | '/checkout/$slug'
    | '/eventos/$slug'
    | '/feedback/$slug'
    | '/inscricao/$slug'
    | '/jogadores/$playerId'
    | '/organizador/controle'
    | '/organizador/eventos'
    | '/organizador/financeiro'
    | '/organizador/inscricoes'
    | '/organizador/novo-evento'
    | '/organizador/plano'
    | '/reembolso/$paymentId'
    | '/admin/'
    | '/eventos/'
    | '/organizador/'
    | '/admin/denuncias/$id'
    | '/admin/organizadores/$id'
    | '/admin/pagamentos/$id'
    | '/organizador/alterar-evento/$slug'
    | '/organizador/sorteio/$slug'
    | '/admin/denuncias/'
    | '/admin/organizadores/'
    | '/admin/pagamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ao-vivo'
    | '/arenas'
    | '/cadastro'
    | '/configuracoes'
    | '/denunciar'
    | '/escolher-perfil'
    | '/juiz'
    | '/login'
    | '/meus-feedbacks'
    | '/meus-jogos'
    | '/minhas-inscricoes'
    | '/notificacoes'
    | '/onboarding'
    | '/parceiros'
    | '/placar'
    | '/ranking'
    | '/trocar-dupla'
    | '/admin/arenas'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/feedbacks'
    | '/admin/financeiro'
    | '/admin/planos'
    | '/admin/publicidade'
    | '/admin/reembolsos'
    | '/admin/usuarios'
    | '/checkout/$slug'
    | '/eventos/$slug'
    | '/feedback/$slug'
    | '/inscricao/$slug'
    | '/jogadores/$playerId'
    | '/organizador/controle'
    | '/organizador/eventos'
    | '/organizador/financeiro'
    | '/organizador/inscricoes'
    | '/organizador/novo-evento'
    | '/organizador/plano'
    | '/reembolso/$paymentId'
    | '/admin'
    | '/eventos'
    | '/organizador'
    | '/admin/denuncias/$id'
    | '/admin/organizadores/$id'
    | '/admin/pagamentos/$id'
    | '/organizador/alterar-evento/$slug'
    | '/organizador/sorteio/$slug'
    | '/admin/denuncias'
    | '/admin/organizadores'
    | '/admin/pagamentos'
  id:
    | '__root__'
    | '/'
    | '/ao-vivo'
    | '/arenas'
    | '/cadastro'
    | '/configuracoes'
    | '/denunciar'
    | '/escolher-perfil'
    | '/juiz'
    | '/login'
    | '/meus-feedbacks'
    | '/meus-jogos'
    | '/minhas-inscricoes'
    | '/notificacoes'
    | '/onboarding'
    | '/parceiros'
    | '/placar'
    | '/ranking'
    | '/trocar-dupla'
    | '/admin/arenas'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/feedbacks'
    | '/admin/financeiro'
    | '/admin/planos'
    | '/admin/publicidade'
    | '/admin/reembolsos'
    | '/admin/usuarios'
    | '/checkout/$slug'
    | '/eventos/$slug'
    | '/feedback/$slug'
    | '/inscricao/$slug'
    | '/jogadores/$playerId'
    | '/organizador/controle'
    | '/organizador/eventos'
    | '/organizador/financeiro'
    | '/organizador/inscricoes'
    | '/organizador/novo-evento'
    | '/organizador/plano'
    | '/reembolso/$paymentId'
    | '/admin/'
    | '/eventos/'
    | '/organizador/'
    | '/admin/denuncias/$id'
    | '/admin/organizadores/$id'
    | '/admin/pagamentos/$id'
    | '/organizador/alterar-evento/$slug'
    | '/organizador/sorteio/$slug'
    | '/admin/denuncias/'
    | '/admin/organizadores/'
    | '/admin/pagamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AoVivoRoute: typeof AoVivoRoute
  ArenasRoute: typeof ArenasRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DenunciarRoute: typeof DenunciarRoute
  EscolherPerfilRoute: typeof EscolherPerfilRoute
  JuizRoute: typeof JuizRoute
  LoginRoute: typeof LoginRoute
  MeusFeedbacksRoute: typeof MeusFeedbacksRoute
  MeusJogosRoute: typeof MeusJogosRoute
  MinhasInscricoesRoute: typeof MinhasInscricoesRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OnboardingRoute: typeof OnboardingRoute
  ParceirosRoute: typeof ParceirosRoute
  PlacarRoute: typeof PlacarRoute
  RankingRoute: typeof RankingRoute
  TrocarDuplaRoute: typeof TrocarDuplaRoute
  AdminArenasRoute: typeof AdminArenasRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminFeedbacksRoute: typeof AdminFeedbacksRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminPublicidadeRoute: typeof AdminPublicidadeRoute
  AdminReembolsosRoute: typeof AdminReembolsosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  EventosSlugRoute: typeof EventosSlugRoute
  FeedbackSlugRoute: typeof FeedbackSlugRoute
  InscricaoSlugRoute: typeof InscricaoSlugRoute
  JogadoresPlayerIdRoute: typeof JogadoresPlayerIdRoute
  OrganizadorControleRoute: typeof OrganizadorControleRoute
  OrganizadorEventosRoute: typeof OrganizadorEventosRoute
  OrganizadorFinanceiroRoute: typeof OrganizadorFinanceiroRoute
  OrganizadorInscricoesRoute: typeof OrganizadorInscricoesRoute
  OrganizadorNovoEventoRoute: typeof OrganizadorNovoEventoRoute
  OrganizadorPlanoRoute: typeof OrganizadorPlanoRoute
  ReembolsoPaymentIdRoute: typeof ReembolsoPaymentIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  OrganizadorIndexRoute: typeof OrganizadorIndexRoute
  AdminDenunciasIdRoute: typeof AdminDenunciasIdRoute
  AdminOrganizadoresIdRoute: typeof AdminOrganizadoresIdRoute
  AdminPagamentosIdRoute: typeof AdminPagamentosIdRoute
  OrganizadorAlterarEventoSlugRoute: typeof OrganizadorAlterarEventoSlugRoute
  OrganizadorSorteioSlugRoute: typeof OrganizadorSorteioSlugRoute
  AdminDenunciasIndexRoute: typeof AdminDenunciasIndexRoute
  AdminOrganizadoresIndexRoute: typeof AdminOrganizadoresIndexRoute
  AdminPagamentosIndexRoute: typeof AdminPagamentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arenas': {
      id: '/arenas'
      path: '/arenas'
      fullPath: '/arenas'
      preLoaderRoute: typeof ArenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denunciar': {
      id: '/denunciar'
      path: '/denunciar'
      fullPath: '/denunciar'
      preLoaderRoute: typeof DenunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolher-perfil': {
      id: '/escolher-perfil'
      path: '/escolher-perfil'
      fullPath: '/escolher-perfil'
      preLoaderRoute: typeof EscolherPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juiz': {
      id: '/juiz'
      path: '/juiz'
      fullPath: '/juiz'
      preLoaderRoute: typeof JuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-feedbacks': {
      id: '/meus-feedbacks'
      path: '/meus-feedbacks'
      fullPath: '/meus-feedbacks'
      preLoaderRoute: typeof MeusFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-jogos': {
      id: '/meus-jogos'
      path: '/meus-jogos'
      fullPath: '/meus-jogos'
      preLoaderRoute: typeof MeusJogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-inscricoes': {
      id: '/minhas-inscricoes'
      path: '/minhas-inscricoes'
      fullPath: '/minhas-inscricoes'
      preLoaderRoute: typeof MinhasInscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placar': {
      id: '/placar'
      path: '/placar'
      fullPath: '/placar'
      preLoaderRoute: typeof PlacarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-dupla': {
      id: '/trocar-dupla'
      path: '/trocar-dupla'
      fullPath: '/trocar-dupla'
      preLoaderRoute: typeof TrocarDuplaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/arenas': {
      id: '/admin/arenas'
      path: '/admin/arenas'
      fullPath: '/admin/arenas'
      preLoaderRoute: typeof AdminArenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedbacks': {
      id: '/admin/feedbacks'
      path: '/admin/feedbacks'
      fullPath: '/admin/feedbacks'
      preLoaderRoute: typeof AdminFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/admin/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/publicidade': {
      id: '/admin/publicidade'
      path: '/admin/publicidade'
      fullPath: '/admin/publicidade'
      preLoaderRoute: typeof AdminPublicidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reembolsos': {
      id: '/admin/reembolsos'
      path: '/admin/reembolsos'
      fullPath: '/admin/reembolsos'
      preLoaderRoute: typeof AdminReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$slug': {
      id: '/feedback/$slug'
      path: '/feedback/$slug'
      fullPath: '/feedback/$slug'
      preLoaderRoute: typeof FeedbackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$slug': {
      id: '/inscricao/$slug'
      path: '/inscricao/$slug'
      fullPath: '/inscricao/$slug'
      preLoaderRoute: typeof InscricaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/$playerId': {
      id: '/jogadores/$playerId'
      path: '/jogadores/$playerId'
      fullPath: '/jogadores/$playerId'
      preLoaderRoute: typeof JogadoresPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/': {
      id: '/organizador/'
      path: '/organizador'
      fullPath: '/organizador/'
      preLoaderRoute: typeof OrganizadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/controle': {
      id: '/organizador/controle'
      path: '/organizador/controle'
      fullPath: '/organizador/controle'
      preLoaderRoute: typeof OrganizadorControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/eventos': {
      id: '/organizador/eventos'
      path: '/organizador/eventos'
      fullPath: '/organizador/eventos'
      preLoaderRoute: typeof OrganizadorEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/financeiro': {
      id: '/organizador/financeiro'
      path: '/organizador/financeiro'
      fullPath: '/organizador/financeiro'
      preLoaderRoute: typeof OrganizadorFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/inscricoes': {
      id: '/organizador/inscricoes'
      path: '/organizador/inscricoes'
      fullPath: '/organizador/inscricoes'
      preLoaderRoute: typeof OrganizadorInscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/novo-evento': {
      id: '/organizador/novo-evento'
      path: '/organizador/novo-evento'
      fullPath: '/organizador/novo-evento'
      preLoaderRoute: typeof OrganizadorNovoEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/plano': {
      id: '/organizador/plano'
      path: '/organizador/plano'
      fullPath: '/organizador/plano'
      preLoaderRoute: typeof OrganizadorPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso/$paymentId': {
      id: '/reembolso/$paymentId'
      path: '/reembolso/$paymentId'
      fullPath: '/reembolso/$paymentId'
      preLoaderRoute: typeof ReembolsoPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/denuncias/': {
      id: '/admin/denuncias/'
      path: '/admin/denuncias'
      fullPath: '/admin/denuncias/'
      preLoaderRoute: typeof AdminDenunciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/denuncias/$id': {
      id: '/admin/denuncias/$id'
      path: '/admin/denuncias/$id'
      fullPath: '/admin/denuncias/$id'
      preLoaderRoute: typeof AdminDenunciasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizadores/': {
      id: '/admin/organizadores/'
      path: '/admin/organizadores'
      fullPath: '/admin/organizadores/'
      preLoaderRoute: typeof AdminOrganizadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizadores/$id': {
      id: '/admin/organizadores/$id'
      path: '/admin/organizadores/$id'
      fullPath: '/admin/organizadores/$id'
      preLoaderRoute: typeof AdminOrganizadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pagamentos/': {
      id: '/admin/pagamentos/'
      path: '/admin/pagamentos'
      fullPath: '/admin/pagamentos/'
      preLoaderRoute: typeof AdminPagamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pagamentos/$id': {
      id: '/admin/pagamentos/$id'
      path: '/admin/pagamentos/$id'
      fullPath: '/admin/pagamentos/$id'
      preLoaderRoute: typeof AdminPagamentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/alterar-evento/$slug': {
      id: '/organizador/alterar-evento/$slug'
      path: '/organizador/alterar-evento/$slug'
      fullPath: '/organizador/alterar-evento/$slug'
      preLoaderRoute: typeof OrganizadorAlterarEventoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizador/sorteio/$slug': {
      id: '/organizador/sorteio/$slug'
      path: '/organizador/sorteio/$slug'
      fullPath: '/organizador/sorteio/$slug'
      preLoaderRoute: typeof OrganizadorSorteioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AoVivoRoute: AoVivoRoute,
  ArenasRoute: ArenasRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DenunciarRoute: DenunciarRoute,
  EscolherPerfilRoute: EscolherPerfilRoute,
  JuizRoute: JuizRoute,
  LoginRoute: LoginRoute,
  MeusFeedbacksRoute: MeusFeedbacksRoute,
  MeusJogosRoute: MeusJogosRoute,
  MinhasInscricoesRoute: MinhasInscricoesRoute,
  NotificacoesRoute: NotificacoesRoute,
  OnboardingRoute: OnboardingRoute,
  ParceirosRoute: ParceirosRoute,
  PlacarRoute: PlacarRoute,
  RankingRoute: RankingRoute,
  TrocarDuplaRoute: TrocarDuplaRoute,
  AdminArenasRoute: AdminArenasRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminFeedbacksRoute: AdminFeedbacksRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminPublicidadeRoute: AdminPublicidadeRoute,
  AdminReembolsosRoute: AdminReembolsosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  EventosSlugRoute: EventosSlugRoute,
  FeedbackSlugRoute: FeedbackSlugRoute,
  InscricaoSlugRoute: InscricaoSlugRoute,
  JogadoresPlayerIdRoute: JogadoresPlayerIdRoute,
  OrganizadorControleRoute: OrganizadorControleRoute,
  OrganizadorEventosRoute: OrganizadorEventosRoute,
  OrganizadorFinanceiroRoute: OrganizadorFinanceiroRoute,
  OrganizadorInscricoesRoute: OrganizadorInscricoesRoute,
  OrganizadorNovoEventoRoute: OrganizadorNovoEventoRoute,
  OrganizadorPlanoRoute: OrganizadorPlanoRoute,
  ReembolsoPaymentIdRoute: ReembolsoPaymentIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  OrganizadorIndexRoute: OrganizadorIndexRoute,
  AdminDenunciasIdRoute: AdminDenunciasIdRoute,
  AdminOrganizadoresIdRoute: AdminOrganizadoresIdRoute,
  AdminPagamentosIdRoute: AdminPagamentosIdRoute,
  OrganizadorAlterarEventoSlugRoute: OrganizadorAlterarEventoSlugRoute,
  OrganizadorSorteioSlugRoute: OrganizadorSorteioSlugRoute,
  AdminDenunciasIndexRoute: AdminDenunciasIndexRoute,
  AdminOrganizadoresIndexRoute: AdminOrganizadoresIndexRoute,
  AdminPagamentosIndexRoute: AdminPagamentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
